// Code generated by protoc-gen-go. DO NOT EDIT.
// source: swag-engine.proto

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The health request message (it's empty)
type HealthRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthRequest) Reset()         { *m = HealthRequest{} }
func (m *HealthRequest) String() string { return proto.CompactTextString(m) }
func (*HealthRequest) ProtoMessage()    {}
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_swag_engine_f71cffaa5f9f33e4, []int{0}
}
func (m *HealthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthRequest.Unmarshal(m, b)
}
func (m *HealthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthRequest.Marshal(b, m, deterministic)
}
func (dst *HealthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthRequest.Merge(dst, src)
}
func (m *HealthRequest) XXX_Size() int {
	return xxx_messageInfo_HealthRequest.Size(m)
}
func (m *HealthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HealthRequest proto.InternalMessageInfo

// The health response message containing the health status
type HealthReply struct {
	Healthstatus         string   `protobuf:"bytes,1,opt,name=healthstatus" json:"healthstatus,omitempty"`
	Processedevents      int32    `protobuf:"varint,2,opt,name=processedevents" json:"processedevents,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthReply) Reset()         { *m = HealthReply{} }
func (m *HealthReply) String() string { return proto.CompactTextString(m) }
func (*HealthReply) ProtoMessage()    {}
func (*HealthReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_swag_engine_f71cffaa5f9f33e4, []int{1}
}
func (m *HealthReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthReply.Unmarshal(m, b)
}
func (m *HealthReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthReply.Marshal(b, m, deterministic)
}
func (dst *HealthReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthReply.Merge(dst, src)
}
func (m *HealthReply) XXX_Size() int {
	return xxx_messageInfo_HealthReply.Size(m)
}
func (m *HealthReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthReply.DiscardUnknown(m)
}

var xxx_messageInfo_HealthReply proto.InternalMessageInfo

func (m *HealthReply) GetHealthstatus() string {
	if m != nil {
		return m.Healthstatus
	}
	return ""
}

func (m *HealthReply) GetProcessedevents() int32 {
	if m != nil {
		return m.Processedevents
	}
	return 0
}

// The mom post request message
type MomPostRequest struct {
	Momtype              string   `protobuf:"bytes,1,opt,name=momtype" json:"momtype,omitempty"`
	Momdefinition        string   `protobuf:"bytes,2,opt,name=momdefinition" json:"momdefinition,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MomPostRequest) Reset()         { *m = MomPostRequest{} }
func (m *MomPostRequest) String() string { return proto.CompactTextString(m) }
func (*MomPostRequest) ProtoMessage()    {}
func (*MomPostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_swag_engine_f71cffaa5f9f33e4, []int{2}
}
func (m *MomPostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MomPostRequest.Unmarshal(m, b)
}
func (m *MomPostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MomPostRequest.Marshal(b, m, deterministic)
}
func (dst *MomPostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MomPostRequest.Merge(dst, src)
}
func (m *MomPostRequest) XXX_Size() int {
	return xxx_messageInfo_MomPostRequest.Size(m)
}
func (m *MomPostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MomPostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MomPostRequest proto.InternalMessageInfo

func (m *MomPostRequest) GetMomtype() string {
	if m != nil {
		return m.Momtype
	}
	return ""
}

func (m *MomPostRequest) GetMomdefinition() string {
	if m != nil {
		return m.Momdefinition
	}
	return ""
}

// The mom post response message
type MomPostReply struct {
	Deploymenterror      string   `protobuf:"bytes,1,opt,name=deploymenterror" json:"deploymenterror,omitempty"`
	Momid                string   `protobuf:"bytes,2,opt,name=momid" json:"momid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MomPostReply) Reset()         { *m = MomPostReply{} }
func (m *MomPostReply) String() string { return proto.CompactTextString(m) }
func (*MomPostReply) ProtoMessage()    {}
func (*MomPostReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_swag_engine_f71cffaa5f9f33e4, []int{3}
}
func (m *MomPostReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MomPostReply.Unmarshal(m, b)
}
func (m *MomPostReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MomPostReply.Marshal(b, m, deterministic)
}
func (dst *MomPostReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MomPostReply.Merge(dst, src)
}
func (m *MomPostReply) XXX_Size() int {
	return xxx_messageInfo_MomPostReply.Size(m)
}
func (m *MomPostReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MomPostReply.DiscardUnknown(m)
}

var xxx_messageInfo_MomPostReply proto.InternalMessageInfo

func (m *MomPostReply) GetDeploymenterror() string {
	if m != nil {
		return m.Deploymenterror
	}
	return ""
}

func (m *MomPostReply) GetMomid() string {
	if m != nil {
		return m.Momid
	}
	return ""
}

func init() {
	proto.RegisterType((*HealthRequest)(nil), "protobuf.HealthRequest")
	proto.RegisterType((*HealthReply)(nil), "protobuf.HealthReply")
	proto.RegisterType((*MomPostRequest)(nil), "protobuf.MomPostRequest")
	proto.RegisterType((*MomPostReply)(nil), "protobuf.MomPostReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EngineClient is the client API for Engine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EngineClient interface {
	// Requires health
	GetHealth(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthReply, error)
	PostMoM(ctx context.Context, in *MomPostRequest, opts ...grpc.CallOption) (*MomPostReply, error)
	PostStamper(ctx context.Context, in *MomPostRequest, opts ...grpc.CallOption) (*MomPostReply, error)
}

type engineClient struct {
	cc *grpc.ClientConn
}

func NewEngineClient(cc *grpc.ClientConn) EngineClient {
	return &engineClient{cc}
}

func (c *engineClient) GetHealth(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthReply, error) {
	out := new(HealthReply)
	err := c.cc.Invoke(ctx, "/protobuf.Engine/GetHealth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) PostMoM(ctx context.Context, in *MomPostRequest, opts ...grpc.CallOption) (*MomPostReply, error) {
	out := new(MomPostReply)
	err := c.cc.Invoke(ctx, "/protobuf.Engine/PostMoM", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) PostStamper(ctx context.Context, in *MomPostRequest, opts ...grpc.CallOption) (*MomPostReply, error) {
	out := new(MomPostReply)
	err := c.cc.Invoke(ctx, "/protobuf.Engine/PostStamper", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EngineServer is the server API for Engine service.
type EngineServer interface {
	// Requires health
	GetHealth(context.Context, *HealthRequest) (*HealthReply, error)
	PostMoM(context.Context, *MomPostRequest) (*MomPostReply, error)
	PostStamper(context.Context, *MomPostRequest) (*MomPostReply, error)
}

func RegisterEngineServer(s *grpc.Server, srv EngineServer) {
	s.RegisterService(&_Engine_serviceDesc, srv)
}

func _Engine_GetHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).GetHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Engine/GetHealth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).GetHealth(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_PostMoM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MomPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).PostMoM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Engine/PostMoM",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).PostMoM(ctx, req.(*MomPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_PostStamper_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MomPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).PostStamper(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Engine/PostStamper",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).PostStamper(ctx, req.(*MomPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Engine_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.Engine",
	HandlerType: (*EngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHealth",
			Handler:    _Engine_GetHealth_Handler,
		},
		{
			MethodName: "PostMoM",
			Handler:    _Engine_PostMoM_Handler,
		},
		{
			MethodName: "PostStamper",
			Handler:    _Engine_PostStamper_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "swag-engine.proto",
}

func init() { proto.RegisterFile("swag-engine.proto", fileDescriptor_swag_engine_f71cffaa5f9f33e4) }

var fileDescriptor_swag_engine_f71cffaa5f9f33e4 = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x90, 0x3d, 0x4f, 0xf3, 0x30,
	0x14, 0x85, 0xdf, 0xbc, 0x52, 0x5b, 0x7a, 0xdb, 0x52, 0x61, 0xf1, 0x11, 0x75, 0xaa, 0x2c, 0x86,
	0x2c, 0x64, 0x80, 0xb9, 0x03, 0x03, 0x82, 0x25, 0xa8, 0x0a, 0x23, 0x53, 0x4a, 0x6e, 0xdb, 0x48,
	0xb1, 0xaf, 0xb1, 0x6f, 0x40, 0xf9, 0x89, 0xfc, 0x2b, 0x94, 0x2f, 0x50, 0x0a, 0x13, 0x93, 0x75,
	0xce, 0xb1, 0x1f, 0xdf, 0x7b, 0xe0, 0xc4, 0xbd, 0x27, 0xbb, 0x2b, 0xd4, 0xbb, 0x4c, 0x63, 0x68,
	0x2c, 0x31, 0x89, 0xa3, 0xfa, 0xd8, 0x14, 0x5b, 0x39, 0x87, 0xd9, 0x03, 0x26, 0x39, 0xef, 0x63,
	0x7c, 0x2d, 0xd0, 0xb1, 0x7c, 0x86, 0x49, 0x67, 0x98, 0xbc, 0x14, 0x12, 0xa6, 0xfb, 0x5a, 0x3a,
	0x4e, 0xb8, 0x70, 0xbe, 0xb7, 0xf4, 0x82, 0x71, 0xdc, 0xf3, 0x44, 0x00, 0x73, 0x63, 0xe9, 0x05,
	0x9d, 0xc3, 0x14, 0xdf, 0x50, 0xb3, 0xf3, 0xff, 0x2f, 0xbd, 0x60, 0x10, 0x1f, 0xda, 0x72, 0x0d,
	0xc7, 0x11, 0xa9, 0x35, 0x39, 0x6e, 0xbf, 0x13, 0x3e, 0x8c, 0x14, 0x29, 0x2e, 0x0d, 0xb6, 0xe8,
	0x4e, 0x8a, 0x4b, 0x98, 0x29, 0x52, 0x29, 0x6e, 0x33, 0x9d, 0x71, 0x46, 0xba, 0x66, 0x8e, 0xe3,
	0xbe, 0x29, 0x1f, 0x61, 0xfa, 0x45, 0xac, 0xe6, 0x0d, 0x60, 0x9e, 0xa2, 0xc9, 0xa9, 0x54, 0xa8,
	0x19, 0xad, 0x25, 0xdb, 0x72, 0x0f, 0x6d, 0x71, 0x0a, 0x03, 0x45, 0x2a, 0x4b, 0x5b, 0x6e, 0x23,
	0xae, 0x3f, 0x3c, 0x18, 0xde, 0xd5, 0x55, 0x89, 0x15, 0x8c, 0xef, 0x91, 0x9b, 0x32, 0xc4, 0x45,
	0xd8, 0x55, 0x16, 0xf6, 0xfa, 0x5a, 0x9c, 0xfd, 0x0c, 0x4c, 0x5e, 0xca, 0x7f, 0x62, 0x05, 0xa3,
	0x6a, 0xac, 0x88, 0x22, 0xe1, 0x7f, 0xdf, 0xe9, 0xaf, 0xbf, 0x38, 0xff, 0x25, 0x69, 0x9e, 0xdf,
	0xc2, 0xa4, 0x92, 0x4f, 0x9c, 0x28, 0x83, 0xf6, 0x2f, 0x88, 0xcd, 0xb0, 0x0e, 0x6e, 0x3e, 0x03,
	0x00, 0x00, 0xff, 0xff, 0xd8, 0x44, 0xc3, 0x76, 0x01, 0x02, 0x00, 0x00,
}
