// Code generated by protoc-gen-go. DO NOT EDIT.
// source: swag-engine.proto

/*
Package protobuf is a generated protocol buffer package.

It is generated from these files:
	swag-engine.proto

It has these top-level messages:
	HealthRequest
	HealthReply
	MomPostRequest
	MomPostReply
*/
package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The health request message (it's empty)
type HealthRequest struct {
}

func (m *HealthRequest) Reset()                    { *m = HealthRequest{} }
func (m *HealthRequest) String() string            { return proto.CompactTextString(m) }
func (*HealthRequest) ProtoMessage()               {}
func (*HealthRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// The health response message containing the health status
type HealthReply struct {
	Healthstatus    string `protobuf:"bytes,1,opt,name=healthstatus" json:"healthstatus,omitempty"`
	Processedevents int32  `protobuf:"varint,2,opt,name=processedevents" json:"processedevents,omitempty"`
}

func (m *HealthReply) Reset()                    { *m = HealthReply{} }
func (m *HealthReply) String() string            { return proto.CompactTextString(m) }
func (*HealthReply) ProtoMessage()               {}
func (*HealthReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HealthReply) GetHealthstatus() string {
	if m != nil {
		return m.Healthstatus
	}
	return ""
}

func (m *HealthReply) GetProcessedevents() int32 {
	if m != nil {
		return m.Processedevents
	}
	return 0
}

// The mom post request message
type MomPostRequest struct {
	Momtype       string `protobuf:"bytes,1,opt,name=momtype" json:"momtype,omitempty"`
	Momdefinition string `protobuf:"bytes,2,opt,name=momdefinition" json:"momdefinition,omitempty"`
}

func (m *MomPostRequest) Reset()                    { *m = MomPostRequest{} }
func (m *MomPostRequest) String() string            { return proto.CompactTextString(m) }
func (*MomPostRequest) ProtoMessage()               {}
func (*MomPostRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MomPostRequest) GetMomtype() string {
	if m != nil {
		return m.Momtype
	}
	return ""
}

func (m *MomPostRequest) GetMomdefinition() string {
	if m != nil {
		return m.Momdefinition
	}
	return ""
}

// The mom post response message
type MomPostReply struct {
	Deploymenterror string `protobuf:"bytes,1,opt,name=deploymenterror" json:"deploymenterror,omitempty"`
	Momid           string `protobuf:"bytes,2,opt,name=momid" json:"momid,omitempty"`
}

func (m *MomPostReply) Reset()                    { *m = MomPostReply{} }
func (m *MomPostReply) String() string            { return proto.CompactTextString(m) }
func (*MomPostReply) ProtoMessage()               {}
func (*MomPostReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *MomPostReply) GetDeploymenterror() string {
	if m != nil {
		return m.Deploymenterror
	}
	return ""
}

func (m *MomPostReply) GetMomid() string {
	if m != nil {
		return m.Momid
	}
	return ""
}

func init() {
	proto.RegisterType((*HealthRequest)(nil), "protobuf.HealthRequest")
	proto.RegisterType((*HealthReply)(nil), "protobuf.HealthReply")
	proto.RegisterType((*MomPostRequest)(nil), "protobuf.MomPostRequest")
	proto.RegisterType((*MomPostReply)(nil), "protobuf.MomPostReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Engine service

type EngineClient interface {
	// Requires health
	GetHealth(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthReply, error)
	PostMoM(ctx context.Context, in *MomPostRequest, opts ...grpc.CallOption) (*MomPostReply, error)
}

type engineClient struct {
	cc *grpc.ClientConn
}

func NewEngineClient(cc *grpc.ClientConn) EngineClient {
	return &engineClient{cc}
}

func (c *engineClient) GetHealth(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthReply, error) {
	out := new(HealthReply)
	err := grpc.Invoke(ctx, "/protobuf.Engine/GetHealth", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) PostMoM(ctx context.Context, in *MomPostRequest, opts ...grpc.CallOption) (*MomPostReply, error) {
	out := new(MomPostReply)
	err := grpc.Invoke(ctx, "/protobuf.Engine/PostMoM", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Engine service

type EngineServer interface {
	// Requires health
	GetHealth(context.Context, *HealthRequest) (*HealthReply, error)
	PostMoM(context.Context, *MomPostRequest) (*MomPostReply, error)
}

func RegisterEngineServer(s *grpc.Server, srv EngineServer) {
	s.RegisterService(&_Engine_serviceDesc, srv)
}

func _Engine_GetHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).GetHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Engine/GetHealth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).GetHealth(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_PostMoM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MomPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).PostMoM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Engine/PostMoM",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).PostMoM(ctx, req.(*MomPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Engine_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.Engine",
	HandlerType: (*EngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHealth",
			Handler:    _Engine_GetHealth_Handler,
		},
		{
			MethodName: "PostMoM",
			Handler:    _Engine_PostMoM_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "swag-engine.proto",
}

func init() { proto.RegisterFile("swag-engine.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xbf, 0x4f, 0xfb, 0x30,
	0x10, 0xc5, 0xbf, 0xf9, 0x4a, 0x6d, 0xc9, 0xd1, 0x12, 0x61, 0xf1, 0x23, 0xea, 0x54, 0x59, 0x0c,
	0x59, 0xc8, 0x00, 0x73, 0x47, 0x04, 0x4b, 0x50, 0x95, 0x95, 0x29, 0x25, 0xd7, 0x36, 0x52, 0xec,
	0x33, 0xf6, 0x05, 0x94, 0x7f, 0x80, 0xbf, 0x1b, 0xd5, 0x4d, 0x40, 0x29, 0x4c, 0xd6, 0x7b, 0xcf,
	0xfe, 0xf8, 0xee, 0xc1, 0xb9, 0xfb, 0x28, 0xb6, 0xb7, 0xa8, 0xb7, 0x95, 0xc6, 0xd4, 0x58, 0x62,
	0x12, 0x27, 0xfe, 0x58, 0x37, 0x1b, 0x19, 0xc1, 0xec, 0x09, 0x8b, 0x9a, 0x77, 0x39, 0xbe, 0x35,
	0xe8, 0x58, 0xbe, 0xc0, 0x69, 0x6f, 0x98, 0xba, 0x15, 0x12, 0xa6, 0x3b, 0x2f, 0x1d, 0x17, 0xdc,
	0xb8, 0x38, 0x58, 0x04, 0x49, 0x98, 0x0f, 0x3c, 0x91, 0x40, 0x64, 0x2c, 0xbd, 0xa2, 0x73, 0x58,
	0xe2, 0x3b, 0x6a, 0x76, 0xf1, 0xff, 0x45, 0x90, 0x8c, 0xf2, 0x63, 0x5b, 0xae, 0xe0, 0x2c, 0x23,
	0xb5, 0x22, 0xc7, 0xdd, 0x77, 0x22, 0x86, 0x89, 0x22, 0xc5, 0xad, 0xc1, 0x0e, 0xdd, 0x4b, 0x71,
	0x03, 0x33, 0x45, 0xaa, 0xc4, 0x4d, 0xa5, 0x2b, 0xae, 0x48, 0x7b, 0x66, 0x98, 0x0f, 0x4d, 0xf9,
	0x0c, 0xd3, 0x6f, 0xe2, 0x7e, 0xde, 0x04, 0xa2, 0x12, 0x4d, 0x4d, 0xad, 0x42, 0xcd, 0x68, 0x2d,
	0xd9, 0x8e, 0x7b, 0x6c, 0x8b, 0x0b, 0x18, 0x29, 0x52, 0x55, 0xd9, 0x71, 0x0f, 0xe2, 0xee, 0x33,
	0x80, 0xf1, 0x83, 0xaf, 0x4a, 0x2c, 0x21, 0x7c, 0x44, 0x3e, 0x94, 0x21, 0xae, 0xd3, 0xbe, 0xb2,
	0x74, 0xd0, 0xd7, 0xfc, 0xf2, 0x77, 0x60, 0xea, 0x56, 0xfe, 0x13, 0x4b, 0x98, 0xec, 0xc7, 0xca,
	0x28, 0x13, 0xf1, 0xcf, 0x9d, 0xe1, 0xfa, 0xf3, 0xab, 0x3f, 0x12, 0xff, 0x7c, 0x3d, 0xf6, 0xc1,
	0xfd, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x89, 0xd9, 0x99, 0xab, 0xbe, 0x01, 0x00, 0x00,
}
