// Code generated by protoc-gen-go. DO NOT EDIT.
// source: swag-engine.proto

/*
Package protobuf is a generated protocol buffer package.

It is generated from these files:
	swag-engine.proto

It has these top-level messages:
	HealthRequest
	HealthReply
*/
package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message (it's empty)
type HealthRequest struct {
}

func (m *HealthRequest) Reset()                    { *m = HealthRequest{} }
func (m *HealthRequest) String() string            { return proto.CompactTextString(m) }
func (*HealthRequest) ProtoMessage()               {}
func (*HealthRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// The response message containing the health status
type HealthReply struct {
	Healthstatus    string `protobuf:"bytes,1,opt,name=healthstatus" json:"healthstatus,omitempty"`
	Processedevents int32  `protobuf:"varint,2,opt,name=processedevents" json:"processedevents,omitempty"`
}

func (m *HealthReply) Reset()                    { *m = HealthReply{} }
func (m *HealthReply) String() string            { return proto.CompactTextString(m) }
func (*HealthReply) ProtoMessage()               {}
func (*HealthReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HealthReply) GetHealthstatus() string {
	if m != nil {
		return m.Healthstatus
	}
	return ""
}

func (m *HealthReply) GetProcessedevents() int32 {
	if m != nil {
		return m.Processedevents
	}
	return 0
}

func init() {
	proto.RegisterType((*HealthRequest)(nil), "protobuf.HealthRequest")
	proto.RegisterType((*HealthReply)(nil), "protobuf.HealthReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Health service

type HealthClient interface {
	// Requires health
	GetHealth(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthReply, error)
}

type healthClient struct {
	cc *grpc.ClientConn
}

func NewHealthClient(cc *grpc.ClientConn) HealthClient {
	return &healthClient{cc}
}

func (c *healthClient) GetHealth(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthReply, error) {
	out := new(HealthReply)
	err := grpc.Invoke(ctx, "/protobuf.Health/GetHealth", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Health service

type HealthServer interface {
	// Requires health
	GetHealth(context.Context, *HealthRequest) (*HealthReply, error)
}

func RegisterHealthServer(s *grpc.Server, srv HealthServer) {
	s.RegisterService(&_Health_serviceDesc, srv)
}

func _Health_GetHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServer).GetHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Health/GetHealth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServer).GetHealth(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Health_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.Health",
	HandlerType: (*HealthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHealth",
			Handler:    _Health_GetHealth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "swag-engine.proto",
}

func init() { proto.RegisterFile("swag-engine.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 162 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x2e, 0x4f, 0x4c,
	0xd7, 0x4d, 0xcd, 0x4b, 0xcf, 0xcc, 0x4b, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00,
	0x53, 0x49, 0xa5, 0x69, 0x4a, 0xfc, 0x5c, 0xbc, 0x1e, 0xa9, 0x89, 0x39, 0x25, 0x19, 0x41, 0xa9,
	0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x4a, 0xd1, 0x5c, 0xdc, 0x30, 0x81, 0x82, 0x9c, 0x4a, 0x21, 0x25,
	0x2e, 0x9e, 0x0c, 0x30, 0xb7, 0xb8, 0x24, 0xb1, 0xa4, 0xb4, 0x58, 0x82, 0x51, 0x81, 0x51, 0x83,
	0x33, 0x08, 0x45, 0x4c, 0x48, 0x83, 0x8b, 0xbf, 0xa0, 0x28, 0x3f, 0x39, 0xb5, 0xb8, 0x38, 0x35,
	0x25, 0xb5, 0x2c, 0x35, 0xaf, 0xa4, 0x58, 0x82, 0x49, 0x81, 0x51, 0x83, 0x35, 0x08, 0x5d, 0xd8,
	0xc8, 0x9d, 0x8b, 0x0d, 0x62, 0xb8, 0x90, 0x2d, 0x17, 0xa7, 0x7b, 0x6a, 0x09, 0x94, 0x23, 0xae,
	0x07, 0x73, 0x8f, 0x1e, 0x8a, 0x63, 0xa4, 0x44, 0x31, 0x25, 0x0a, 0x72, 0x2a, 0x95, 0x18, 0x92,
	0xd8, 0xc0, 0xe2, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd0, 0x3a, 0x9b, 0xb6, 0xdc, 0x00,
	0x00, 0x00,
}
