def elastest_url = ''
node(){
    elastest(tss: [], surefireReportsPattern: '**/target/surefire-reports/TEST-*.xml', project: 'ETinET', sut: 11) {
        stage ('docker container')
            def mycontainer = docker.image('elastest/ci-docker-e2e:latest')
            mycontainer.pull()
            mycontainer.inside()  {
                sh 'env'
                stage ('prepare test')
                    git 'https://github.com/elastest/elastest-torm.git'
                    elastest_url = env.ET_SUT_PROTOCOL + '://elastest:3xp3r1m3nt47@' + env.ET_SUT_HOST + ':' + env.ET_SUT_PORT
                    
                stage ("Run tests")
                    try {
                        sh "cd e2e-test; bash ./start-instance.sh "+elastestURL
                    } catch(e) {
                        echo 'Err: ' + e.toString()
                    } finally {
                        step([$class: 'JUnitResultArchiver', testDataPublishers: [[$class: 'AttachmentPublisher']], testResults: '**/target/surefire-reports/TEST-*.xml'])
                    }
            }
    }
}

